### ISSUE TITLE
Technical Spike: user input forms with node 

### ISSUE THREAD

**Issue by lucyrose93** [yvonne-liu/week6-soFly-FACt#51]
How can we write data inputted by our user to the database that they have submitted via a form? 

Comment findings below...

**Comment by lucyrose93** [comment]
https://www.sitepoint.com/creating-and-handling-forms-in-node-js/

**Comment by yvonne-liu** [comment]
https://blog.risingstack.com/node-js-database-tutorial/

**Comment by yvonne-liu** [comment]
https://github.com/felixge/node-formidable

**Comment by samatar26** [comment]
http://stackoverflow.com/questions/15772394/how-to-upload-display-and-save-images-using-node-js-and-express Great example using express
