### ISSUE TITLE
script in adduser.html

### ISSUE THREAD

**Issue by Jbarget** [yvonne-liu/week6-soFly-FACt#76]
https://github.com/yvonne-liu/week6-soFly-FACt/blob/master/public/adduser.html#L53-L58

I'd personally say to keep a "separation of concerns" and keep js in a js file

NB. Im not sure if you need this script anyway, since you actually want to default action of the form:
to post the form data to the endpoint 

https://github.com/yvonne-liu/week6-soFly-FACt/blob/master/public/adduser.html#L20

**Comment by samatar26** [comment]
:+1:  Removing it and redirecting it the proper way serverside

**Comment by Jbarget** [comment]
nice
